export const productive_apps = [
  // Original
  "code", "vscodium", "cursor", "neovim", "nvim", "vim", "emacs", "zed",
  "sublime_text", "intellij", "webstorm", "pycharm", "goland", "rider",
  "clion", "rustrover", "android-studio", "xcode", "eclipse", "netbeans",
  "alacritty", "kitty", "wezterm", "foot", "ghostty", "konsole",
  "gnome-terminal", "terminator", "tmux", "obsidian", "notion", "logseq",
  "joplin", "anki", "libreoffice", "thunderbird", "postman", "insomnia",
  "dbeaver", "pgadmin", "mongodb-compass", "figma", "gimp", "inkscape",
  "blender", "kdenlive", "obs", "davinci-resolve", "audacity", "docker",
  "virtualbox", "vmware", "wireshark", "burpsuite", "ghidra", "fritzing",
  "kicad", "freecad", "openscad", "unity", "godot", "unreal", "arduino",
  "rstudio", "jupyter", "spyder", "matlab", "octave", "texstudio", "zotero",
  "mendeley", "calibre", "drawio", "miro", "excalidraw", "tableplus",
  "datagrip", "firefox-developer", "chromium",
  // Expanded: Editors & IDEs
  "helix", "kakoune", "lapce", "fleet", "geany", "notepad++", "brackets",
  "atom", "bluej", "qtcreator", "rad-studio", "appcode", "rubymine", "phpstorm",
  "textmate", "coda", "bbedit", "nova",
  // Expanded: Terminals & CLI tools
  "iterm2", "hyper", "cmder", "conemu", "tilix", "rxvt", "st", "guake", "yakuake",
  "warp", "tabby", "xterm", "screen", "zellij", "htop", "btop", "glances",
  "lazygit", "lazydocker", "k9s", "fzf", "ripgrep", "jq", "sed", "awk", "curl", "wget",
  // Expanded: Databases & Infrastructure
  "navicat", "heidisql", "sqlitebrowser", "robomongo", "studio3t", "sequelpro",
  "sequelace", "beekeeper", "redisinsight", "dbvisualizer", "lens", "terraform",
  "vagrant", "ansible", "puppet", "chef", "podman", "minikube",
  // Expanded: Productivity & Note-taking
  "roam", "appflowy", "standardnotes", "evernote", "onenote", "bear", "craft",
  "simplenote", "turtl", "cherrytree", "zim", "xmind", "mindnode", "freemind",
  "todoist", "ticktick", "things3", "omnifocus", "taskwarrior", "toggl", "clockify",
  // Expanded: Creative & Engineering
  "affinity-designer", "affinity-photo", "affinity-publisher", "coreldraw", "krita",
  "aseprite", "darktable", "rawtherapee", "lightroom", "premiere", "aftereffects",
  "illustrator", "indesign", "lmms", "ableton", "flstudio", "reaper", "bitwig",
  "logicpro", "sibelius", "musescore", "autocad", "solidworks", "fusion360", "inventor",
  "maya", "3dsmax", "cinema4d", "zbrush", "houdini", "nuke", "natron",
  // Expanded: Browsers & Office
  "brave", "vivaldi", "librewolf", "waterfox", "arc", "thorium", "ungoogled-chromium",
  "msoffice", "word", "excel", "powerpoint", "onlyoffice", "wps-office", "abiword",
  // Expanded: Science & Data
  "spss", "sas", "stata", "minitab", "mathematica", "maple", "labview", "qgis", "arcgis",
  "tableau", "powerbi", "rapidminer", "knime", "gephi", "cytoscape"
];

export const productive_keywords = [
// Original
  "github", "gitlab", "bitbucket", "stackoverflow", "stackexchange",
  "leetcode", "hackerrank", "codeforces", "codewars", "geeksforgeeks",
  "neetcode", "exercism", "topcoder", "docs", "documentation", "wiki",
  "mdn", "devdocs", "api reference", "tutorial", "course", "udemy",
  "coursera", "edx", "khan academy", "freecodecamp", "w3schools",
  "codecademy", "pluralsight", "skillshare", "brilliant",
  "mit opencourseware", "medium.com", "dev.to", "hashnode",
  "smashingmagazine", "css-tricks", "arxiv", "research", "journal",
  "springer", "ieee", "google scholar", "pubmed", "semantic scholar",
  "researchgate", "academia.edu", "jira", "linear", "trello", "asana",
  "notion.so", "confluence", "monday.com", "clickup", "basecamp",
  "todoist", "ticktick", "slack", "google docs", "google sheets",
  "google slides", "google drive", "google calendar", "google meet",
  "zoom meeting", "microsoft teams", "overleaf", "latex", "chatgpt",
  "claude", "perplexity", "copilot", "bard", "npm", "pypi", "crates.io",
  "pkg.go.dev", "rubygems", "maven", "nuget", "packagist", "docker hub",
  "vercel", "netlify", "aws console", "azure portal", "google cloud",
  "heroku", "digitalocean", "cloudflare", "railway", "supabase",
  "firebase", "planetscale", "grafana", "datadog", "sentry", "kibana",
  "prometheus", "jenkins", "circleci", "travis", "github actions",
  "terraform", "ansible", "kubernetes", "portainer", "rancher",
  "figma.com", "canva", "adobe", "photopea", "dribbble", "behance",
  "google fonts", "coolors", "colorhunt", "unsplash", "pexels",
  "stackoverflow.com", "regex101", "jsonformatter", "postman.com",
  "swagger", "rapidapi", "hoppscotch", "replit", "codepen", "codesandbox",
  "stackblitz", "glitch", "kaggle", "huggingface", "paperswithcode",
  "tensorflow", "pytorch", "wandb", "colab", "deepnote", "observable",
  "d3js", "threejs", "codingame", "adventofcode", "projecteuler",
  "rosettacode", "codeproject", "baeldung", "tutorialspoint", "javatpoint",
  "programiz", "real python", "rust book", "go.dev", "cppreference",
  "learn.microsoft", "developer.apple", "developer.android", "react.dev",
  "vuejs.org", "angular.io", "nextjs.org", "svelte.dev", "tailwindcss",
  "bootstrap", "materialui",
  // Expanded: Tech Stacks & Languages
  "python", "javascript", "typescript", "rust", "golang", "java", "c++", "c#", "ruby",
  "php", "swift", "kotlin", "dart", "scala", "haskell", "clojure", "elixir", "erlang",
  "zig", "nim", "lua", "perl", "bash", "powershell", "sql", "nosql", "graphql", "rest api",
  "grpc", "webrtc", "websockets", "oauth", "jwt", "dockerfile", "yaml", "json", "toml",
  // Expanded: Frameworks & Libraries
  "django", "flask", "fastapi", "spring boot", "laravel", "ruby on rails", "expressjs",
  "nestjs", "trpc", "prisma", "sequelize", "typeorm", "mongoose", "sqlalchemy", "alembic",
  "pandas", "numpy", "scipy", "scikit-learn", "keras", "opencv", "matplotlib", "seaborn",
  "pytest", "jest", "mocha", "chai", "cypress", "selenium", "playwright", "puppeteer",
  "webpack", "vite", "rollup", "esbuild", "parcel", "babel", "eslint", "prettier",
  // Expanded: Cloud & DevOps
  "aws s3", "aws ec2", "aws lambda", "dynamodb", "rds", "ecs", "eks", "fargate",
  "gcp compute", "gcp storage", "bigquery", "firebase db", "azure functions",
  "azure devops", "bitrise", "argocd", "fluxcd", "istio", "envoy", "nginx", "apache",
  "caddy", "traefik", "haproxy", "elasticsearch", "logstash", "fluentd", "new relic",
  "dynatrace", "appdynamics", "splunk", "pagerduty", "opsgenie",
  // Expanded: Learning & Academics
  "sciencedirect", "jstor", "wiley", "nature", "science.org", "cell.com", "ssrn",
  "biorxiv", "medrxiv", "chemrxiv", "project gutenberg", "libgen", "sci-hub",
  "oreilly", "packt", "manning", "datacamp", "dataquest", "algoexpert", "educative",
  "frontendmentor", "cssbattle", "sqlzoo", "linuxjourney", "vtex", "shopify dev"
];

export const unproductive_keywords = [
// Original
  "youtube", "netflix", "twitch", "disney+", "hulu", "hbo max",
  "crunchyroll", "funimation", "prime video", "peacock", "paramount+",
  "apple tv", "plex", "jellyfin", "kodi", "reddit", "twitter", "x.com",
  "facebook", "instagram", "tiktok", "snapchat", "pinterest", "tumblr",
  "threads", "mastodon", "bluesky", "discord", "telegram", "whatsapp",
  "messenger", "wechat", "signal", "viber", "line", "spotify",
  "soundcloud", "apple music", "deezer", "tidal", "pandora",
  "youtube music", "last.fm", "amazon shopping", "ebay", "aliexpress",
  "wish", "shein", "etsy", "walmart", "target", "alibaba", "shopee",
  "lazada", "9gag", "imgur", "buzzfeed", "boredpanda", "ifunny",
  "knowyourmeme", "fandom", "tvtropes", "ranker", "distractify", "game",
  "steam", "lutris", "heroic", "minecraft", "valorant",
  "league of legends", "fortnite", "apex legends", "overwatch", "dota",
  "csgo", "counter-strike", "genshin", "roblox", "among us",
  "call of duty", "fifa", "madden", "nba 2k", "rocket league",
  "fall guys", "elden ring", "baldurs gate", "starfield", "diablo",
  "world of warcraft", "final fantasy", "runescape", "path of exile",
  "lost ark", "destiny", "halo", "pubg", "warzone", "escape from tarkov",
  "dead by daylight", "phasmophobia", "lethal company", "palworld",
  "helldivers", "poker", "chess.com/play", "lichess.org/play", "solitaire",
  "minesweeper", "wordle", "candy crush", "clash royale", "brawl stars",
  "dating", "tinder", "bumble", "hinge", "match.com", "okcupid",
  "onlyfans", "patreon", "kickstarter", "gofundme", "bet365", "draftkings",
  "fanduel", "gambling", "casino", "slots", "sports betting", "pornhub",
  "xvideos", "xnxx", "rule34", "e621", "gelbooru", "danbooru", "nhentai",
  "hanime", "gossip", "tmz", "dailymail", "cosmopolitan", "people.com",
  "eonline", "usmagazine", "horoscope", "astrology", "meme", "shitpost",
  "copypasta", "greentext", "4chan", "8kun", "kiwifarms",
  // Expanded: Social Media & Forums
  "quora", "yahoo answers", "nextdoor", "meetup", "bereal", "yikyak", "kik", "omegle",
  "chatroulette", "vrchat", "second life", "habbo", "club penguin", "fark", "somethingawful",
  "mumsnet", "resetera", "neogaf", "gamefaqs", "ign", "gamespot", "kotaku", "polygon",
  "dexerto", "sportskeeda", "barstool", "deadspin",
  // Expanded: Streaming & Entertainment
  "vimeo", "dailymotion", "rumble", "bilibili", "nicovideo", "afreecatv", "kick.com",
  "tubi", "pluto tv", "shudder", "amc+", "starz", "showtime", "cinemax", "vudu",
  "fubo", "sling tv", "directv stream", "philo", "discovery+", "itv", "bbc iplayer",
  "channel 4", "myanimelist", "anilist", "mangatown", "mangadex", "webtoon", "tapas",
  "wattpad", "fanfiction.net", "archiveofourown", "ao3", "goodreads", "letterboxd",
  // Expanded: Shopping & Consumerism
  "temu", "dhgate", "banggood", "dealextreme", "woot", "slickdeals", "retailmenot",
  "groupon", "overstock", "wayfair", "macys", "nordstrom", "asos", "zara", "h&m",
  "forever21", "urban outfitters", "stockx", "goat", "grailed", "depop", "poshmark",
  "mercari", "vinted", "craigslist", "kijiji", "gumtree", "zillow", "trulia", "redfin",
  // Expanded: Specific Games & Platforms
  "epic games", "origin", "ea app", "ubisoft connect", "battlenet", "gog galaxy",
  "itch.io", "xbox game pass", "playstation network", "nintendo switch online",
  "gta online", "gta v", "red dead redemption", "cyberpunk 2077", "witcher 3",
  "skyrim", "fallout", "mass effect", "borderlands", "terraria", "stardew valley",
  "animal crossing", "smash bros", "mario kart", "zelda", "pokemon", "hearthstone",
  "magic the gathering", "yu-gi-oh", "marvel snap", "teamfight tactics", "auto chess",
  "rust game", "dayz", "ark survival", "conan exiles", "valheim", "sea of thieves",
  "no mans sky", "rainbow six siege", "smite", "paladins", "warframe", "brawlhalla",
  "guilty gear", "street fighter", "tekken", "mortal kombat",
  // Expanded: News (Non-tech/Distracting) & Lifestyle
  "fox news", "cnn", "msnbc", "huffpost", "breitbart", "drudge report", "vice",
  "vox", "gq", "esquire", "vogue", "vanity fair", "refinery29", "goop", "perezhilton",
  "complex", "hypebeast", "highsnobiety", "espn", "bleacher report", "the athletic",
  "skysports", "fantasy football", "strava", "myfitnesspal",
  // Expanded: More NSFW / Distracting content
  "chaturbate", "bongacams", "stripchat", "camsoda", "manyvids", "fansly",
  "spankbang", "eporner", "motherless", "heavy-r", "redtube", "youporn",
  "tube8", "xhamster", "literotica", "lushstories", "noodlemagazine",
  // Expanded: Finance & Crypto (Often rabbit holes)
  "coinmarketcap", "coingecko", "binance", "coinbase", "kraken", "kucoin",
  "robinhood", "etoro", "webull", "fidelity", "vanguard", "wsb", "wallstreetbets",
  "stocktwits", "seekingalpha", "motley fool", "zacks"
];
